/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Form: typeof import('@primevue/forms/form')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    IconCarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconMdiAccountBox: typeof import('~icons/mdi/account-box')['default']
    IconMdiCarbonAccessibility: typeof import('~icons/mdi/carbon-accessibility')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IEmojioneMono: typeof import('~icons/emojione/mono')['default']
    IEmojioneMonotone: typeof import('~icons/emojione/monotone')['default']
    'IEmojioneMonotoneLetter-': typeof import('~icons/emojione-monotone/letter-')['default']
    IEmojioneMonotoneLetterN: typeof import('~icons/emojione-monotone/letter-n')['default']
    IEmojioneMonotoneLetterX: typeof import('~icons/emojione-monotone/letter-x')['default']
    IMdiAccountBox: typeof import('~icons/mdi/account-box')['default']
    IMdiArrowDown: typeof import('~icons/mdi/arrow-down')['default']
    IMdiFile: typeof import('~icons/mdi/file')['default']
    IMdiFire: typeof import('~icons/mdi/fire')['default']
    IMdiFolder: typeof import('~icons/mdi/folder')['default']
    IMdiHot: typeof import('~icons/mdi/hot')['default']
    IMdiLeadPencil: typeof import('~icons/mdi/lead-pencil')['default']
    IMdiStar: typeof import('~icons/mdi/star')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ISimpleIconsTelegram: typeof import('~icons/simple-icons/telegram')['default']
    Layouts: typeof import('./src/components/layouts/index.vue')['default']
    Login: typeof import('./src/components/layouts/login.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Tree: typeof import('primevue/tree')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
