/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    IconCarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconMdiAccountBox: typeof import('~icons/mdi/account-box')['default']
    IconMdiCarbonAccessibility: typeof import('~icons/mdi/carbon-accessibility')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IEmojioneMono: typeof import('~icons/emojione/mono')['default']
    IEmojioneMonotone: typeof import('~icons/emojione/monotone')['default']
    'IEmojioneMonotoneLetter-': typeof import('~icons/emojione-monotone/letter-')['default']
    IEmojioneMonotoneLetterN: typeof import('~icons/emojione-monotone/letter-n')['default']
    IEmojioneMonotoneLetterX: typeof import('~icons/emojione-monotone/letter-x')['default']
    IMdiAccountBox: typeof import('~icons/mdi/account-box')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ISimpleIconsTelegram: typeof import('~icons/simple-icons/telegram')['default']
    Layouts: typeof import('./src/components/layouts/index.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
